#!/usr/bin/env python3

import os
import argparse
import sys 

if sys.platform != 'win32':
    sys.exit()

parser = argparse.ArgumentParser(
    prog='aattr',
    description='windows 显示/隐藏文件',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter
)


parser.add_argument('--show',
                    # 提供值时 '--show ./asd'
                    type=str,

                    # 未提供值时 '--show '
                    nargs='?', const='',

                    # 命令中不存在此选项时 ' '
                    default=None,
                    help='显示文件，如果没有提供文件，则显示当前目录下所有文件')

parser.add_argument('--hide',
                    type=str,
                    nargs='?', const='',
                    default=None,
                    help='隐藏文件，如果没有提供文件，则隐藏当前目录下所有文件')

args = parser.parse_args()


if args.hide is not None:
    if args.hide:
        os.system(f"attrib.exe +h +s +r {args.hide}")
    else:
        os.system('attrib.exe +h +s +r /S /D')
    sys.exit()

if args.show is not None:
    if args.show:
        os.system(f"attrib.exe -h -s -r {args.show}")
    else:
        os.system('attrib.exe -h -s -r /S /D')
        os.system('attrib.exe +h +s +r ./desktop.ini')
    sys.exit()
