#!/usr/bin/env python3

import argparse
import os
import sys

parser = argparse.ArgumentParser(
    prog='afpp',
    description='''
Flutetr 快速脚本
    ''',
    formatter_class=argparse.RawTextHelpFormatter
)

parser.add_argument('-pub', '--publish', action='store_true',
                    default=None, help='发布包命令')
parser.add_argument('-r', '--reset', action='store_true',
                    default=None, help='设置china的安装包环境')
parser.add_argument('--check', action='store_true',
                    default=None, help='检查包是否有错误')
parser.add_argument('--port', type=int, default=19996, help='发布时设置本地代理代理端口号')
parser.add_argument('-code', '--codegen', action='store_true',
                    default=None, help='生成*.g.dart文件')
parser.add_argument('--build', action='store_true',
                    default=None, help='分包打包APK')
parser.add_argument('--emulator', type=str, nargs='?',
                    const='', default=None, help='启动 Android 设备模拟器')

args = parser.parse_args()

if args.check:
    os.system('flutter packages pub lish --dry-run')

if args.build:
    os.system('flutter build apk --split-per-abi')


def resetENV():
    del os.environ['http_proxy']
    del os.environ['https_proxy']
    os.environ['PUB_HOSTED_URL'] = "https://pub.flutter-io.cn"
    os.environ['FLUTTER_STORAGE_BASE_URL'] = "https://storage.flutter-io.cn"


def publishENV():
    del os.environ['PUB_HOSTED_URL']
    del os.environ['FLUTTER_STORAGE_BASE_URL']
    os.environ['http_proxy'] = f"http://127.0.0.1:{args.port}"
    os.environ['https_proxy'] = f"https://127.0.0.1:{args.port}"


# 发布：设置环境变量，并执行发布命令
if args.publish:
    publishENV()
    os.system('flutter packages pub lish')
    resetENV()

# 发布成功，重置环境变量
if args.reset:
    resetENV()

if args.codegen:
    os.system(
        'flutter packages pub run build_runner watch --delete-conflicting-outputs')

if args.emulator is not None:
    ANDROID_HOME = os.environ.get("ANDROID_HOME", None)
    if not ANDROID_HOME:
        print("没找到 ANDROID_HOME 环境变量")
        sys.exit(1)

    emulator_exe_path = os.path.join(ANDROID_HOME, 'emulator', 'emulator.exe')
    if not os.path.exists(emulator_exe_path):
        print(f"没找到 {emulator_exe_path}")
        sys.exit(1)

    if args.emulator:
        os.system(f'{emulator_exe_path} -avd {args.emulator}')  # 启动指定模拟器
    else:
        os.system(f'{emulator_exe_path} -list-avds')  # 模拟器列表
