#!/usr/bin/env python3


import os
import sys
from ast import literal_eval
from PIL import Image

# aimg "bg.png" "(1920, 1080)"
size = literal_eval(sys.argv[-1:][0])

if type(size) is not tuple:
    sys.exit()

for infile in sys.argv[1:-1]:
    if not os.path.exists(infile):
        continue

    (f1, f2) = os.path.splitext(infile)
    outfile = f"{f1}-out{f2}"
    try:
        with Image.open(infile) as im:
            im.thumbnail(size)
            im.save(outfile, im.format)
    except OSError:
        print("cannot create thumbnail for", infile)
