#!/usr/bin/env python3

import sys
import re
import os
import shutil
import stat
from sys import exit

if len(sys.argv) == 1:
    print('必须设置保存目录!')
    exit()

# 保存的文件目录
saveDir = sys.argv[1]

# 避免windows上的空格文件
saveDir = re.sub(r' ', '\\ ', saveDir)

def readonly_handler(func, path, execinfo):
    os.chmod(path, stat.S_IWRITE)
    func(path)

success = os.system(
    f"git clone https://github.com/januwA/webpack-scaffold.git {saveDir}")

if success != 0:
    exit()

git_path = os.path.join('./', saveDir, '.git')

if os.path.exists(git_path):
    shutil.rmtree(git_path, onerror=readonly_handler)

print('''
See also:

# https://webpack.js.org/
# https://www.webpackjs.com/
# https://github.com/januwA/webpack-scaffold.git
''')
